# Test TOML File
# Simple key-value pairs
money = 100             # Integer
poney = 100             
title = "TOML Example"  # String (Basic)
version = 1.0           # Float
enabled = true          # Boolean
pete = true
